### ISSUE TITLE
Possible(?) security hole in Friendship

### ISSUE THREAD

**Issue by seivan** [hackforrefugees/blending-matching#1]
https://github.com/hackforrefugees/blending-matching/blob/master/app/controllers/friendships_controller.rb#L16-L31

You should do that `Friendship#find` on `current_profile.friendship` or whatever the scope is called instead of a direct query on the model. 

Otherwise I might be able to remove Friendship requests by looping over your incremented IDs.

I say might because I am not sure if you got safe guards elsewhere.

**Comment by olssonr** [comment]
Hi Seivan,

Good point! Thanks for reminding us. We will definitely fix this before we try to push it.
